alias fd="fdfind"
alias fm="y"
alias pyhttp="python3 -m http.server"
alias pyftpd="python3 -m pyftpdlib"
alias feh-bg="feh --bg-fill --no-fehbg"
alias yt-dlp-album="yt-dlp --config ~/.config/yt-dlp/config-album"
alias yt-dlp-playlist="yt-dlp --config ~/.config/yt-dlp/config-playlist"
