[mgr]
prepend_keymap = [
    # Enter shell
    { on = '!', run  = 'shell "$SHELL" --block', desc = "Open shell here" },

    # Q to close tabs + quit
    { on  = "q", run = "close" },

    # Bookmarks
    # {on = "m", run = "plugin bookmarks save"},
    # {on = "'", run = "plugin bookmarks jump"},
    # {on = ["b", "d"],  run = "plugin bookmarks delete"},

    # Move parent directories
    { on  = "K", run = "plugin parent-arrow -1" },
    { on  = "J", run = "plugin parent-arrow 1" },

    # Better renaming
    #{ on   = "R", run  = "shell 'vimv \"$@\"' --block", desc = "Bulk rename (vimv)" },

    # Compress
    { on = [ "z" ], run="plugin compress", desc="Archive selected files" },
    { on   = "Z", run  = "plugin zoxide" },

    # Plugins
    { on = "<Enter>", run  = "plugin smart-enter" },
    { on = [ "c", "m" ], run  = "plugin chmod" },
    { on   = "F", run  = "plugin fzf" },

    # Open with shell command
    { on = "<C-o>", run="plugin open-with-cmd -- block", desc = "Open with command in the terminal" },

    # Mounting
    { on = [ "M", "m" ], run = "plugin mount", desc = "Mount plugin" },

    # Misc
    { on = [ "<C-p>", "w", "f" ], run = "shell 'feh --bg-fill --no-fehbg \"$@\"' --block"},
    { on = [ "<C-p>", "w", "a" ], run = "shell 'awww img \"$@\"' --block"},
    { on = [ "<C-p>", "g"], run="shell 'nvim -c \"tab Git\"' --block", desc = "Open git fugitive" },

    # Shortcuts - Home
    { on = ["'", "a"], run="cd ~/Audio" },
    { on = ["'", "c"], run="cd ~/Code" },
    { on = ["'", "d"], run="cd ~/Draws" },
    { on = ["'", "i"], run="cd ~/Img" },
    { on = ["'", "m"], run="cd ~/Music" },
    { on = ["'", "s"], run="cd ~/Sync" },
    { on = ["'", "t"], run="cd ~/Temp" },
    { on = ["'", "v"], run="cd ~/Videos" },

    { on = ["g", ".", "b"], run="cd ~/.local/bin" },
    { on = ["g", ".", "c"], run="cd ~/.config" },
    { on = ["g", ".", "l"], run="cd ~/.local/" },
    { on = ["g", ".", "v"], run="cd ~/.var" },

    # Shortcuts - Root
    { on = ["g", "/", "e"], run="cd /etc" },
    { on = ["g", "/", "l"], run="cd /usr/local/" },
    { on = ["g", "/", "m"], run="cd /mnt" },
    { on = ["g", "/", "o"], run="cd /opt" },
    { on = ["g", "/", "r"], run="cd /" },
    { on = ["g", "/", "s"], run="cd /usr/share" },
    { on = ["g", "/", "t"], run="cd /tmp" },
    { on = ["g", "/", "u"], run="cd /usr" },
    { on = ["g", "/", "v"], run="cd /var" },
    { on = ["g", "/", "g"], run="cd /run/user/1000/gvfs" },

    # Mount
    { on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },
    { on = [ "M", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },
    { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },
    { on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject --force", desc = "Select device then force to eject/unmount" },
    { on = [ "M", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
    { on = [ "M", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
    { on = [ "M", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },
    { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device", desc = "Select device then jump to its mount point" },
]

